collections_dir: content
collections:
  team:
    output: true
    sort_by: order
    permalink: /:collection/members/:name
  teaching_current_semester:
    output: true
    permalink: /teaching/:path
  teaching_past_semesters:
    output: true
    permalink: /teaching/:path
  news:
    output: true
    sort_by: date
    permalink: /:collection/:title
  software:
    sort_by: date