site: RSiM Site
group_name: RSiM
rsim_mainpage: https://rsim.berlin

tu_berlin_mainpage: https://tu.berlin
erc_mainpage: https://erc.europa.eu
bmbf_mainpage: https://www.bmbf.de
bmwi_mainpage: https://www.bmwi.de